remote_theme: pages-themes/tactile@v0.2.0
title: "Daniel Van Lewen"
description: "About"
url: "https://dvanlewen.github.io"
baseurl: ""

nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"

social_links:
  github: "https://github.com/dvanlewen"
  linkedin: "https://linkedin.com/in/daniel-van-lewen/"
  email: "mailto:danielvl@bu.com"
